package com.rapyd.toolkit.enums

enum class RefundTypeEnum {
    CASH_PAYOUT_REFUND,
    EWALLET_PAYOUT_REFUND,
    BANK_TRANSFER_PAYOUT_REFUND,
    WALLET_TRANSFER_REFUND,
    CARD_PAYOUT_REFUND,
    COUPON_REFUND
}